owner: Sahalandro
repo: upptimecheck

sites:
  #Production      display: flex; flex-direction: row; flex-wrap: wrap;
  - name: britta-ai
    url: www.britta-ai.de
    timeout: 10000
  - name: gymdistrict
    url: https://gymdistrict.de/
    timeout: 10000
  - name: sportbutler
    url: https://sportbutler.team/
    timeout: 10000
  - name: hüpfburgen-verleih
    url: https://holsteiner-huepfburgenverleih.de/
    timeout: 10000
  - name: ki-helfer-klinik
    url: ki-helfer-klinik.mbd-team.de
    timeout: 10000
  - name: app.ki-helferlein
    url: app.ki-helferlein.de
    timeout: 10000
  - name: ki-helferlein
    url: ki-helferlein.de
    timeout: 10000
  - name: mbd-team
    url: https://mbd-team.de/
    timeout: 10000
  - name: wyngman
    url: https://wyngman.mbd-team.de/
    timeout: 10000
  - name: shiftbutler
    url: https://shiftbutler.mbd-team.de/
    timeout: 10000
  #Staging
  - name: staging.britta-ai
    url: demo.britta-ai.de
    timeout: 10000
  - name: staging.gymdistrict
    url: staging.gymdistrict.mbd-team.de
    timeout: 10000
  - name: staging.herta
    url: herta.mbd-team.de
    timeout: 10000
  - name: staging.holsteiner-huepfburgenverleih
    url: staging.holsteiner-huepfburgenverleih.mbd-team.de
    timeout: 10000
  - name: staging.ki-helfer-general
    url: staging.ki-helfer-general.mbd-team.de
    timeout: 10000
  - name: staging.mbd-team
    url: staging.mbd-team.de
    timeout: 10000
  - name: staging.sportbutler
    url: staging.sportbutler.team
    timeout: 10000
  - name: staging.wyngman
    url: staging.wyngman.mbd-team.de
    timeout: 10000
    
status-website:
  baseUrl: /upptimecheck
  name: MBD-Serverstatus
  #css: ".live-status { display: flex; flex-wrap: wrap; }"
  css: ".live-status {display: grid; grid-template-columns: repeat(3, 2fr); grid-template-rows: repeat(7, 2fr); grid-column-gap: 10px; grid-row-gap: 10px;} .container{max-width: 90%}"

workflowSchedule:
  graphs: "1,*/15 * * * *" #updates the graphs
  responseTime: "*/15 * * * *" #records the reponse time of each endpoint and commits it to git history
  staticSite: "5,*/15 * * * *" #builds and deploys your status page website using GitHub Pages.
  summary: "2,*/15 * * * *" #updates the README of your project with a summary of the response times and generated graphs.
  updateTemplate: "0 0 * * *" #gets update from upptime
  updates: "0 3 * * *"
  uptime: "*/5 * * * *" #checks if your websites are up. If they are down, it creates a new issue in your repository.
