owner: Sahalandro
repo: upptimecheck

sites:
  - name: mbd-team
    url: https://mbd-team.de/
    timeout: 10000
  - name: gymdistrict
    url: https://gymdistrict.de/
    timeout: 10000
  - name: sportbutler
    url: https://sportbutler.team/
    timeout: 10000
  - name: hüpfburgen-verleih
    url: https://holsteiner-huepfburgenverleih.de/
    timeout: 10000

status-website:
  baseUrl: /upptimecheck
  name: MBD-Serverstatus

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
