owner: Sahalandro
repo: upptimecheck

sites:
  #Production      display: flex; flex-direction: row; flex-wrap: wrap;
  - name: "britta-ai.de"
    url: britta-ai.de
    timeout: 10000
  - name: "gymdistrict.de"
    url: gymdistrict.de
    timeout: 10000
  - name: "sportbutler.team"
    url: sportbutler.team
    timeout: 10000
  - name: "holsteiner-huepfburgenverleih.de"
    url: holsteiner-huepfburgenverleih.de
    timeout: 10000
  - name: "ki-helfer-klinik.mbd-team.de"
    url: ki-helfer-klinik.mbd-team.de
    timeout: 10000
  - name: "app.ki-helferlein.de"
    url: app.ki-helferlein.de
    timeout: 10000
  - name: "ki-helferlein.de"
    url: ki-helferlein.de
    timeout: 10000
  - name: "mbd-team.de"
    url: mbd-team.de
    timeout: 10000
  - name: "wyngman.mbd-team.de"
    url: wyngman.mbd-team.de
    timeout: 10000
  - name: "shiftbutler.mbd-team.de"
    url: shiftbutler.mbd-team.de
    timeout: 10000
  #Staging
  - name: "Staging: britta-ai.de"
    url: demo.britta-ai.de
    timeout: 10000
  - name: "Staging: gymdistrict.mbd-team.de"
    url: staging.gymdistrict.mbd-team.de
    timeout: 10000
  - name: "Staging: herta.mbd-team.de"
    url: staging.herta.mbd-team.de
    timeout: 10000
  - name: "Staging: holsteiner-huepfburgenverleih.mbd-team.de"
    url: staging.holsteiner-huepfburgenverleih.mbd-team.de
    timeout: 10000
  - name: "Staging: ki-helfer-general.mbd-team.de"
    url: staging.ki-helfer-general.mbd-team.de
    timeout: 10000
  - name: "Staging: staging.ki-helfer-klinik.mbd-team.de"
    url: staging.ki-helfer-klinik.mbd-team.de
    timeout: 10000
  - name: "Staging: mbd-team.de"
    url: staging.mbd-team.de
    timeout: 10000
  - name: "Staging: sportbutler.team"
    url: staging.sportbutler.team
    timeout: 10000
  - name: "Staging: wyngman.mbd-team.de"
    url: staging.wyngman.mbd-team.de
    timeout: 10000
    
status-website:
  baseUrl: /upptimecheck
  name: MBD-Serverstatus
  css: ".live-status {display: grid; grid-template-columns: repeat(3, 3fr); grid-column-gap: 5px; grid-row-gap: 5px;} .container{max-width: 90%} article + article {margin-top: 0px}"
  js: "const h2= document.createElement('h2');, h2.innerHTML="Staging";"

workflowSchedule:
  graphs: "1,*/15 * * * *" #updates the graphs
  responseTime: "*/15 * * * *" #records the reponse time of each endpoint and commits it to git history
  staticSite: "5,*/15 * * * *" #builds and deploys your status page website using GitHub Pages.
  summary: "2,*/15 * * * *" #updates the README of your project with a summary of the response times and generated graphs.
  updateTemplate: "0 0 * * *" #gets update from upptime
  updates: "0 3 * * *"
  uptime: "*/5 * * * *" #checks if your websites are up. If they are down, it creates a new issue in your repository.
