owner: MBD-Team
repo: upptimecheck

sites:
  #Production
  - name: "britta-ai.de"
    url: https://britta-ai.de/
    timeout: 10000
  - name: "gymdistrict.de"
    url: https://gymdistrict.de/
    timeout: 10000
  - name: "sportbutler.team"
    url: https://sportbutler.team/
    timeout: 10000
  - name: "holsteiner-huepfburgenverleih.de"
    url: https://holsteiner-huepfburgenverleih.de/
    timeout: 10000
  - name: "ki-helfer-klinik.mbd-team.de"
    url: https://ki-helfer-klinik.mbd-team.de/
    timeout: 10000
  - name: "app.ki-helferlein.de"
    url: https://app.ki-helferlein.de/
    timeout: 10000
  - name: "ki-helferlein.de"
    url: https://ki-helferlein.de/
    timeout: 10000
  - name: "mbd-team.de"
    url: https://mbd-team.de/
    timeout: 10000
  - name: "wyngman.mbd-team.de"
    url: https://wyngman.mbd-team.de/
    timeout: 10000
  - name: "shiftbutler.mbd-team.de"
    url: https://shiftbutler.mbd-team.de/
    timeout: 10000
  - name: "herta.mbd-team.de"
    url: https://herta.mbd-team.de/
    timeout: 10000
  #Client
  - name: "Client: allcon-import.de"
    url: https://www.allcon-import.de/
    timeout: 10000
  - name: "Client: www.elbeholz.net"
    url: https://www.elbeholz.net/
    timeout: 10000
  - name: "Client: woelke-sh.de"
    url: https://woelke-sh.de/
    timeout: 10000
  - name: "Client: blumen-für-gudendorf.de"
    url: https://xn--blumen-fr-gudendorf-dbc.de/
    timeout: 10000
  #Staging
  - name: "Staging: britta-ai.de"
    url: demo.britta-ai.de
    timeout: 10000
  - name: "Staging: gymdistrict.mbd-team.de"
    url: staging.gymdistrict.mbd-team.de
    timeout: 10000
  - name: "Staging: herta.mbd-team.de"
    url: staging.herta.mbd-team.de
    timeout: 10000
  - name: "Staging: holsteiner-huepfburgenverleih.mbd-team.de"
    url: staging.holsteiner-huepfburgenverleih.mbd-team.de
    timeout: 10000
  - name: "Staging: ki-helfer-general.mbd-team.de"
    url: staging.ki-helfer-general.mbd-team.de
    timeout: 10000
  - name: "Staging: ki-helfer-klinik.mbd-team.de"
    url: staging.ki-helfer-klinik.mbd-team.de
    timeout: 10000
  - name: "Staging: mbd-team.de"
    url: staging.mbd-team.de
    timeout: 10000
  - name: "Staging: sportbutler.team"
    url: staging.sportbutler.team
    timeout: 10000
  - name: "Staging: wyngman.mbd-team.de"
    url: staging.wyngman.mbd-team.de
    timeout: 10000
    
status-website:
  baseUrl: /upptimecheck
  name: MBD-Serverstatus
  css: ".live-status {display: grid; grid-template-columns: repeat(4, 3fr); grid-column-gap: 5px; grid-row-gap: 5px;} .container{max-width: 90%} article + article {margin-top: 0px} h2{margin-top: 32px}"
  js: "const h2= document.createElement('h2'); h2.innerHTML='Staging';  const grid= document.createElement('grid'); grid.style = 'display: grid; grid-template-columns: repeat(4, 3fr); grid-column-gap: 5px; grid-row-gap: 5px;'; const Client= document.createElement('h2'); Client.innerHTML='Clients'; const grid2= document.createElement('grid2'); grid2.style = 'display: grid; grid-template-columns: repeat(4, 3fr); grid-column-gap: 5px; grid-row-gap: 5px;'; setTimeout(() => {document.querySelector('.live-status').parentElement.appendChild(Client); document.querySelector('.live-status').parentElement.appendChild(grid); Array.from(document.querySelectorAll('article.graph')).filter((s)=>s.innerText.includes('Client:')).forEach(e=>document.querySelector('grid').appendChild(e)); document.querySelector('.live-status').parentElement.appendChild(h2); document.querySelector('.live-status').parentElement.appendChild(grid2); Array.from(document.querySelectorAll('article.graph')).filter((s)=>s.innerText.includes('Staging:')).forEach(e=>document.querySelector('grid2').appendChild(e)); document.querySelector('.live-status').parentElement.appendChild(document.querySelector('.svelte-18y4uo2').parentElement)}, 2000); setInterval(() => {window.location.reload();}, 600000);"
workflowSchedule:
  graphs: "1,*/15 * * * *" #updates the graphs
  responseTime: "*/15 * * * *" #records the reponse time of each endpoint and commits it to git history
  staticSite: "5,*/15 * * * *" #builds and deploys your status page website using GitHub Pages.
  summary: "2,*/15 * * * *" #updates the README of your project with a summary of the response times and generated graphs.
  updateTemplate: "0 0 * * *" #gets update from upptime
  updates: "0 3 * * *"
  uptime: "*/5 * * * *" #checks if your websites are up. If they are down, it creates a new issue in your repository.
